### ISSUE TITLE
write iteration checkpoint include velocity and acceleration

### ISSUE THREAD

**Issue by yuxianglin** [precice/calculix-adapter#22] opened 2019-11-20 18:51 UTC
Hi:

I wonder if we would need to store the inital velocity and acceleration when write iteration checkpoint and reload them when read_iteration_checkpoint? Since when calculix step before synchronization time, it may update the velocity and acceleration, which should be restored when sub-iteration is needed. Currently the adapter seems only restore the displacement

**Comment by uekerman** [comment] 2019-11-21 15:02
Thanks for opening this. Is this a duplicate of #9 or how are both related?

**Comment by yuxianglin** [comment] 2019-11-21 17:47
This might explains why sub-cycling is not working properly

**Comment by uekerman** [comment] 2019-11-24 16:22
I am closing this issue in favor of #9.
Needless to say, we are very open for contributions to the CalculiX adapter. The CalculiX expertise of the preCICE core developers is limited to some extent.

**Closed by uekerman** 2019-11-24 16:22 UTC
